services:
  - type: web
    name: sechahaemal-a-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    envVars:
      - key: PUBLIC_DATA_API_KEY
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: "3.12"
